# Generated by Django 6.0.6 on 2026-07-25 15:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_servicetype'),
        ('students', '0008_student_unique_roll_per_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('starts_at', models.CharField(blank=True, help_text='Month string YYYY-MM', max_length=7, null=True)),
                ('ends_at', models.CharField(blank=True, help_text='Month string YYYY-MM', max_length=7, null=True)),
                ('auto_assigned', models.BooleanField(default=True, help_text='Auto-managed by student service toggle')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_services', to='core.servicetype')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='students.student')),
            ],
            options={
                'verbose_name': 'student service',
                'verbose_name_plural': 'student services',
                'constraints': [models.UniqueConstraint(fields=('student', 'service_type'), name='unique_student_service')],
            },
        ),
    ]
