# Generated by Django 6.0.6 on 2026-09-15 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_agentfinding'),
        ('students', '0009_studentservice'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='student',
            name='unique_roll_per_class',
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(condition=models.Q(('roll__gt', ''), ('deleted_at__isnull', True)), fields=('roll', 'school_class'), name='unique_roll_per_class'),
        ),
    ]
