# Generated by Django 6.0.6 on 2026-07-25 15:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('default_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('frequency', models.CharField(choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly'), ('ONE_TIME', 'One Time')], default='MONTHLY', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'service type',
                'verbose_name_plural': 'service types',
                'ordering': ['name'],
            },
        ),
    ]
