# Generated by Django 6.0.6 on 2026-09-12 08:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_servicetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent', models.CharField(max_length=50)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=20)),
                ('entity_type', models.CharField(blank=True, default='', max_length=50)),
                ('entity_id', models.CharField(blank=True, max_length=100, null=True)),
                ('summary', models.CharField(max_length=500)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acked', 'Acknowledged'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('resolution', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'agent'], name='core_agentf_status_f07c61_idx'), models.Index(fields=['status', '-created_at'], name='core_agentf_status_f8eef7_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('agent', 'entity_type', 'entity_id'), name='unique_open_finding_per_agent_entity')],
            },
        ),
    ]
