# Generated by Django 6.0.6 on 2026-09-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_agentfinding'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='academicyear',
            index=models.Index(fields=['is_active'], name='core_academ_is_acti_01feba_idx'),
        ),
    ]
