# Generated by Django 6.0.6 on 2026-08-06 04:56
# Rewritten: 0008 declared unique_receipt_counter only in STATE (state_operations),
# the constraint was never created in the DB — so the DB-side RemoveConstraint
# from the autogenerated 0016 failed. Use SeparateDatabaseAndState: DB only adds
# the field + new constraint; state swaps the old constraint for the new one.

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_alter_financial_fks_to_protect'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.AddField(
                    model_name='receiptcounter',
                    name='counter_date',
                    field=models.DateField(default=datetime.date.today, help_text='Serial resets daily (YYYYMMDD prefix)'),
                ),
                migrations.AddConstraint(
                    model_name='receiptcounter',
                    constraint=models.UniqueConstraint(fields=('counter_date', 'receipt_type'), name='unique_receipt_counter'),
                ),
            ],
            state_operations=[
                migrations.RemoveConstraint(
                    model_name='receiptcounter',
                    name='unique_receipt_counter',
                ),
                migrations.AddField(
                    model_name='receiptcounter',
                    name='counter_date',
                    field=models.DateField(default=datetime.date.today, help_text='Serial resets daily (YYYYMMDD prefix)'),
                ),
                migrations.AddConstraint(
                    model_name='receiptcounter',
                    constraint=models.UniqueConstraint(fields=('counter_date', 'receipt_type'), name='unique_receipt_counter'),
                ),
            ],
        ),
    ]
