# Generated by Django 6.0.6 on 2026-09-15 03:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_alter_feeschedule_amount_alter_feewaiver_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconciliation',
            name='closing_balance',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='reconciliation',
            name='system_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
