# Generated by Django 6.0.6 on 2026-09-15 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_alter_reconciliation_closing_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_refund',
            field=models.BooleanField(default=False, help_text='True when this reversal row records a real money-out refund; False means a void (as if the original never happened).'),
        ),
    ]
