# Generated by Django 6.0.6 on 2026-09-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0020_transaction_is_refund'),
        ('students', '0010_remove_student_unique_roll_per_class_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='feewaiver',
            index=models.Index(fields=['student', 'active'], name='finance_fee_student_ebd6b8_idx'),
        ),
        migrations.AddIndex(
            model_name='feewaiver',
            index=models.Index(fields=['active', 'approval_status'], name='finance_fee_active_9e1a28_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentallocation',
            index=models.Index(fields=['student', 'fee_schedule', 'period'], name='finance_pay_student_fe2cc3_idx'),
        ),
        migrations.AddIndex(
            model_name='studentfeeassignment',
            index=models.Index(fields=['fee_schedule', 'active'], name='finance_stu_fee_sch_8ca9c1_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['source_account', 'transaction_date'], name='finance_tra_source__8e995d_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['destination_account', 'transaction_date'], name='finance_tra_destina_ffc4fa_idx'),
        ),
    ]
