# Generated by Django 6.0.6 on 2026-08-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_must_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('monitor', 'Monitor'), ('accountant', 'Accountant'), ('super_viewer', 'Super Viewer'), ('viewer', 'Viewer'), ('parent', 'Parent')], default='viewer', max_length=20),
        ),
    ]
