# Generated by Django 6.0.6 on 2026-08-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_servicetype'),
        ('teachers', '0007_add_teacher_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='classteacher',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Lead class teacher — at most one per class'),
        ),
        migrations.AddConstraint(
            model_name='classteacher',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('school_class',), name='one_primary_class_teacher'),
        ),
    ]
