# Generated by Django 6.0.6 on 2026-08-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0006_studentconnectlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='event_type',
            field=models.CharField(choices=[('attendance_marked', 'Attendance Marked'), ('fee_received', 'Fee Received'), ('result_published', 'Result Published'), ('announcement', 'Announcement'), ('dues_reminder', 'Dues Reminder')], max_length=30),
        ),
    ]
