# Generated by Django 6.0.6 on 2026-09-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0007_alter_notificationlog_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='event_type',
            field=models.CharField(choices=[('attendance_marked', 'Attendance Marked'), ('fee_received', 'Fee Received'), ('result_published', 'Result Published'), ('announcement', 'Announcement'), ('dues_reminder', 'Dues Reminder'), ('agent_digest', 'Agent Digest')], max_length=30),
        ),
    ]
