# Generated by Django 6.0.6 on 2026-09-12 13:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0008_alter_notificationlog_event_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='event_type',
            field=models.CharField(choices=[('attendance_marked', 'Attendance Marked'), ('fee_received', 'Fee Received'), ('fee_reversal', 'Fee Reversal'), ('result_published', 'Result Published'), ('announcement', 'Announcement'), ('dues_reminder', 'Dues Reminder'), ('agent_digest', 'Agent Digest')], max_length=30),
        ),
        migrations.CreateModel(
            name='ConnectClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='parents.studentconnectlink')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connect_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'connect claim',
                'verbose_name_plural': 'connect claims',
                'indexes': [models.Index(fields=['link'], name='parents_con_link_id_6309ef_idx'), models.Index(fields=['user'], name='parents_con_user_id_ae4a8a_idx')],
                'constraints': [models.UniqueConstraint(fields=('link', 'user'), name='unique_connect_claim')],
            },
        ),
    ]
