# Generated by Django 6.0.6 on 2026-09-13 00:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0010_alter_notificationlog_event_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pushsubscription',
            constraint=models.UniqueConstraint(fields=('user', 'endpoint'), name='unique_push_user_endpoint'),
        ),
    ]
