# Generated by Django 6.0.7 on 2026-09-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0011_pushsubscription_unique_push_user_endpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='event_type',
            field=models.CharField(choices=[('attendance_marked', 'Attendance Marked'), ('fee_received', 'Fee Received'), ('fee_reversal', 'Fee Reversal'), ('result_published', 'Result Published'), ('announcement', 'Announcement'), ('dues_reminder', 'Dues Reminder'), ('agent_digest', 'Agent Digest'), ('routine_published', 'Routine Published'), ('homework_published', 'Homework Published'), ('diary_created', 'Diary Created')], max_length=30),
        ),
    ]
